
/* Drop Tables */

DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE BOARD
(
	NO number(5) NOT NULL,
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	POSTDATE date DEFAULT SYSDATE,
	HITCOUNT number(7) DEFAULT 0,
	LIKECOUNT number(7) DEFAULT 0,
	ID varchar2(20) NOT NULL,
	PRIMARY KEY (NO)
);


CREATE TABLE COMMENTS
(
	CNO number(5) NOT NULL,
	COMMENTS nvarchar2(100) NOT NULL,
	POSTDATE date DEFAULT SYSDATE,
	ID varchar2(20) NOT NULL,
	NO number(5) NOT NULL,
	PRIMARY KEY (CNO)
);


CREATE TABLE MEMBER
(
	ID varchar2(20) NOT NULL,
	PWD varchar2(20) NOT NULL,
	NAME nvarchar2(20) NOT NULL,
	REGISTRYNUM varchar2(10) NOT NULL,
	ADDRESS nvarchar2(100) NOT NULL,
	INTER varchar2(30),
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE COMMENTS
	ADD FOREIGN KEY (NO)
	REFERENCES BOARD (NO)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE COMMENTS
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;



